name: Update GitHub Stats

on:
  schedule:
    - cron: "0 * * * *"  # Run every hour
  workflow_dispatch:     # Allow manual triggering

jobs:
  update-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      
      - name: Install dependencies
        run: pip install PyGithub requests
      
      - name: Run stats script
        run: python stats.py
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_USERNAME: ${{ github.repository_owner }}
          README_REPO: ${{ github.repository }}
      
      - name: Commit and push changes
        run: |
          git config user.name "${{ github.repository_owner }}"
          git config user.email "${{ github.repository_owner }}@users.noreply.github.com"
          git add README.md
          git diff --quiet && git diff --staged --quiet || (
            git pull --rebase
            git commit --no-edit
            git push
          )
